/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import model.PersonsList;
import model.UsersList;

/**
 *
 * @author Gautam16
 */
public class UserPanel extends javax.swing.JPanel {
    private PersonsList plist;
    private UsersList ulist;
    private MainJFrame mainFrame;
    /**
     * Creates new form LoginPanel
     */
    public UserPanel(MainJFrame mainFrame, PersonsList plist, UsersList ulist) {
        initComponents();
        this.mainFrame = mainFrame;
        this.plist = plist;
        this.ulist = ulist;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane4 = new javax.swing.JSplitPane();
        consolePanel4 = new javax.swing.JPanel();
        btnViewProfile = new javax.swing.JButton();
        btnUpdateProfile = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        workArea1 = new javax.swing.JPanel();

        splitPane4.setPreferredSize(new java.awt.Dimension(400, 300));

        btnViewProfile.setText("View Profile");
        btnViewProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewProfileActionPerformed(evt);
            }
        });

        btnUpdateProfile.setText("Update Profile");
        btnUpdateProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateProfileActionPerformed(evt);
            }
        });

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout consolePanel4Layout = new javax.swing.GroupLayout(consolePanel4);
        consolePanel4.setLayout(consolePanel4Layout);
        consolePanel4Layout.setHorizontalGroup(
            consolePanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consolePanel4Layout.createSequentialGroup()
                .addGroup(consolePanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(consolePanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(consolePanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnViewProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdateProfile)))
                    .addGroup(consolePanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnLogOut)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        consolePanel4Layout.setVerticalGroup(
            consolePanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consolePanel4Layout.createSequentialGroup()
                .addContainerGap(170, Short.MAX_VALUE)
                .addComponent(btnViewProfile)
                .addGap(18, 18, 18)
                .addComponent(btnUpdateProfile)
                .addGap(42, 42, 42)
                .addComponent(btnLogOut)
                .addGap(101, 101, 101))
        );

        splitPane4.setLeftComponent(consolePanel4);

        javax.swing.GroupLayout workArea1Layout = new javax.swing.GroupLayout(workArea1);
        workArea1.setLayout(workArea1Layout);
        workArea1Layout.setHorizontalGroup(
            workArea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        workArea1Layout.setVerticalGroup(
            workArea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        splitPane4.setRightComponent(workArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(splitPane4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(splitPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProfileActionPerformed
        // TODO add your handling code here:
        ViewProfileJPanel viewProfilePanel = new ViewProfileJPanel(plist, ulist);
        splitPane4.setRightComponent(viewProfilePanel);
    }//GEN-LAST:event_btnViewProfileActionPerformed

    private void btnUpdateProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateProfileActionPerformed
        // TODO add your handling code here:
        UpdateProfileJPanel updateProfilePanel = new UpdateProfileJPanel(plist, ulist);
        splitPane4.setRightComponent(updateProfilePanel);
    }//GEN-LAST:event_btnUpdateProfileActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        mainFrame.switchToLoginPanel();
    }//GEN-LAST:event_btnLogOutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnUpdateProfile;
    private javax.swing.JButton btnViewProfile;
    private javax.swing.JPanel consolePanel4;
    private javax.swing.JSplitPane splitPane4;
    private javax.swing.JPanel workArea1;
    // End of variables declaration//GEN-END:variables
}
